aws_access_key = "vfdjdsdsdsdsdjiosdfiooj5643543543jk54"
aws_secret_key = "nowyouareallfuckedyouareallinfectedyouidiots"
aws_key_path = "~/.ssh/fuck.pem"
aws_key_name = "fuck"
aws_region = "us-east-1"
network = "10.10"
